spring.application.name=mamnguqua
spring.datasource.url=jdbc:mysql://localhost:3306/book?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true

spring.datasource.username=root
spring.datasource.password=admin123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.hibernate.ddl-auto=update

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


spring.jpa.show-sql=true

spring.data.web.pageable.serialization-mode=via-dto

spring.jpa.properties.hibernate.format_sql=true

logging.level.org.hibernate.orm.results.bind=trace

server.forward-headers-strategy=framework

spring.web.resources.static-locations=classpath:/static/

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB


# VNPay Sandbox
vnpay.vnp_Url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html

vnpay.vnp_TmnCode=DK2LYCV3

vnpay.vnp_HashSecret=MJCO9H9527FJ5DLYHNFKTYS75T3JIR0G

vnpay.vnp_ReturnUrl=https://effc-2405-4803-db3d-a010-dcb6-a96b-b48e-240b.ngrok-free.app/api/vnpay/vnpay-return

